---
ips:
  - ip: 10.0.1.1
    port: 1
    mac: 9a:ac:fa:d7:7a:b2
    gw: 10.0.1.254
  - ip: 10.0.2.2
    port: 2
    mac: b2:53:c6:d4:bc:18
    gw: 10.0.2.254
  - ip: 10.0.3.3
    port: 3
    mac: c0:d8:00:f3:eb:0d
    gw: 10.0.3.254
  - ip: 10.0.4.4
    port: 4
    mac: de:e4:13:8c:c9:8a
    gw: 10.0.4.254